#!/usr/bin/env python3
"""Automated Content Creation Pipeline.

Demonstrates a complete content creation workflow using CloudCurio agents.
"""

from agents.tools.file_tools import file_writer_tool
from agents.tools.llm_tools import llm_completion_tool
from agents.tools.web_tools import search_engine_tool


def create_blog_post(topic: str, length: str = "medium") -> dict:
    """Create a complete blog post using multi-agent pipeline.

    Args:
        topic: Blog post topic
        length: Content length (short, medium, long)

    Returns:
        Dictionary with blog post and metadata
    """
    print(f"Creating blog post about: {topic}")
    print("=" * 50)

    # Step 1: Research phase
    print("\n[1/4] Researching topic...")
    search = search_engine_tool()
    search_results = search.execute(query=topic, num_results=5)

    if search_results["status"] == "success":
        sources = search_results["results"]
        print(f"  Found {len(sources)} sources")
    else:
        print(f"  Error: {search_results['error']}")
        return {"status": "error", "error": "Research failed"}

    # Step 2: Content generation
    print("\n[2/4] Generating draft content...")
    llm = llm_completion_tool({"temperature": 0.7})

    prompt = f"""Write a {length} blog post about {topic}.

Use these research findings as sources:
{chr(10).join([f"- {s['title']}: {s['snippet']}" for s in sources[:3]])}

Structure:
1. Engaging introduction
2. Main content with 3-5 key points
3. Conclusion with call to action

Make it informative, engaging, and SEO-friendly.
"""

    draft = llm.execute(prompt=prompt)

    if draft["status"] == "success":
        content = draft["text"]
        print(f"  Generated {len(content)} characters")
    else:
        print(f"  Error: {draft['error']}")
        return {"status": "error", "error": "Content generation failed"}

    # Step 3: Enhancement phase
    print("\n[3/4] Enhancing content...")

    enhance_prompt = f"""Improve this blog post:

{content}

Enhancements:
- Add relevant examples
- Improve readability
- Add subheadings
- Include key statistics if mentioned in sources
- Ensure proper flow

Return the enhanced version.
"""

    enhanced = llm.execute(prompt=enhance_prompt, temperature=0.5)

    if enhanced["status"] == "success":
        final_content = enhanced["text"]
        print("  Content enhanced")
    else:
        final_content = content
        print("  Using draft version")

    # Step 4: Save to file
    print("\n[4/4] Saving blog post...")
    filename = f"blog_{topic.lower().replace(' ', '_')}.md"

    writer = file_writer_tool({"base_path": "output"})

    markdown_content = f"""# {topic.title()}

{final_content}

---

## Sources
{chr(10).join([f"- [{s['title']}]({s['url']})" for s in sources[:5]])}

*Generated by CloudCurio AI Agent Framework*
"""

    result = writer.execute(filepath=filename, content=markdown_content)

    if result["status"] == "success":
        print(f"  Saved to {result['filepath']}")
    else:
        print(f"  Error saving: {result['error']}")

    return {
        "status": "success",
        "content": final_content,
        "sources": sources,
        "filepath": result.get("filepath", ""),
        "word_count": len(final_content.split()),
    }


def create_social_media_posts(blog_content: str, platforms: list = None) -> dict:
    """Generate social media posts from blog content.

    Args:
        blog_content: Blog post content
        platforms: List of platforms (twitter, linkedin, facebook)

    Returns:
        Dictionary of posts for each platform
    """
    platforms = platforms or ["twitter", "linkedin"]

    print("\nGenerating social media posts...")
    print("=" * 50)

    llm = llm_completion_tool({"temperature": 0.8})
    posts = {}

    for platform in platforms:
        print(f"\n[{platform.upper()}]")

        if platform == "twitter":
            prompt = f"""Create a Twitter thread (3-5 tweets) promoting this blog post:

{blog_content[:500]}...

Requirements:
- Each tweet under 280 characters
- Engaging and conversational
- Include relevant hashtags
- Start with a hook
"""
        elif platform == "linkedin":
            prompt = f"""Create a LinkedIn post promoting this blog post:

{blog_content[:500]}...

Requirements:
- Professional tone
- 150-300 words
- Include key insights
- End with engagement question
"""
        else:
            prompt = f"""Create a {platform} post promoting this blog post:

{blog_content[:500]}...

Make it engaging and appropriate for {platform}.
"""

        result = llm.execute(prompt=prompt)

        if result["status"] == "success":
            posts[platform] = result["text"]
            preview = result["text"][:100]
            print(f"  Generated: {preview}...")
        else:
            print(f"  Error: {result['error']}")

    return {"status": "success", "posts": posts}


def main():
    """Run automated content creation pipeline."""
    import sys

    # Get topic from command line or use default
    topic = sys.argv[1] if len(sys.argv) > 1 else "AI Agent Frameworks in 2024"

    print("\n🚀 Automated Content Creation Pipeline")
    print("=" * 60)
    print(f"Topic: {topic}\n")

    # Create blog post
    blog_result = create_blog_post(topic, length="medium")

    if blog_result["status"] == "success":
        print("\n✓ Blog post created successfully!")
        print(f"  Word count: {blog_result['word_count']}")
        print(f"  Sources: {len(blog_result['sources'])}")
        print(f"  File: {blog_result['filepath']}")

        # Generate social media posts
        social_result = create_social_media_posts(blog_result["content"])

        if social_result["status"] == "success":
            print("\n✓ Social media posts generated!")
            for platform in social_result["posts"]:
                print(f"  - {platform.upper()}")
    else:
        print(f"\n✗ Failed: {blog_result['error']}")
        return 1

    print("\n" + "=" * 60)
    print("✓ Pipeline complete!")
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
