#!/usr/bin/env python3
"""Data Analysis Automation.

Automated data analysis pipeline using CloudCurio tools.
"""

from agents.tools.file_tools import file_reader_tool, file_writer_tool
from agents.tools.data_tools import csv_processor_tool, data_transform_tool
from agents.tools.llm_tools import llm_completion_tool
import json


def analyze_dataset(filepath: str) -> dict:
    """Analyze a dataset and generate insights.
    
    Args:
        filepath: Path to data file (CSV or JSON)
    
    Returns:
        Analysis results with insights
    """
    print(f"Analyzing dataset: {filepath}")
    print("=" * 60)
    
    # Step 1: Load data
    print("\n[1/5] Loading data...")
    reader = file_reader_tool()
    file_result = reader.execute(filepath=filepath)
    
    if file_result["status"] != "success":
        return {"status": "error", "error": f"Failed to load file: {file_result['error']}"}
    
    print(f"  File loaded: {file_result['size']} bytes")
    
    # Step 2: Parse data
    print("\n[2/5] Parsing data...")
    
    if filepath.endswith('.csv'):
        csv_tool = csv_processor_tool()
        parse_result = csv_tool.execute(data=file_result["content"], action="parse")
    elif filepath.endswith('.json'):
        try:
            records = json.loads(file_result["content"])
            parse_result = {"status": "success", "records": records}
        except Exception as e:
            return {"status": "error", "error": f"JSON parse error: {str(e)}"}
    else:
        return {"status": "error", "error": "Unsupported file format"}
    
    if parse_result["status"] != "success":
        return {"status": "error", "error": "Failed to parse data"}
    
    records = parse_result["records"]
    print(f"  Parsed {len(records)} records")
    
    # Step 3: Calculate statistics
    print("\n[3/5] Calculating statistics...")
    transformer = data_transform_tool()
    
    # Get numeric fields
    if records:
        first_record = records[0]
        numeric_fields = [k for k, v in first_record.items() if isinstance(v, (int, float))]
        print(f"  Found {len(numeric_fields)} numeric fields: {numeric_fields}")
    else:
        return {"status": "error", "error": "No records found"}
    
    statistics = {}
    for field in numeric_fields[:5]:  # Limit to first 5 fields
        # Calculate aggregates
        sum_result = transformer.execute(
            data=records,
            operation="aggregate",
            field=field,
            function="sum"
        )
        avg_result = transformer.execute(
            data=records,
            operation="aggregate",
            field=field,
            function="avg"
        )
        min_result = transformer.execute(
            data=records,
            operation="aggregate",
            field=field,
            function="min"
        )
        max_result = transformer.execute(
            data=records,
            operation="aggregate",
            field=field,
            function="max"
        )
        
        statistics[field] = {
            "sum": sum_result.get("result", 0),
            "avg": avg_result.get("result", 0),
            "min": min_result.get("result", 0),
            "max": max_result.get("result", 0)
        }
    
    print("  Statistics calculated")
    
    # Step 4: Generate insights using LLM
    print("\n[4/5] Generating insights...")
    llm = llm_completion_tool({"temperature": 0.3})
    
    prompt = f"""Analyze this dataset and provide key insights:

Dataset: {filepath}
Total Records: {len(records)}

Statistics:
{json.dumps(statistics, indent=2)}

Sample Records:
{json.dumps(records[:3], indent=2)}

Provide:
1. Key findings (3-5 points)
2. Trends or patterns
3. Anomalies or outliers
4. Recommendations

Be specific and data-driven.
"""
    
    insights_result = llm.execute(prompt=prompt)
    
    if insights_result["status"] == "success":
        insights = insights_result["text"]
        print("  Insights generated")
    else:
        insights = "Failed to generate insights"
        print(f"  Error: {insights_result['error']}")
    
    # Step 5: Generate report
    print("\n[5/5] Generating report...")
    
    report = f"""# Data Analysis Report

## Dataset Information
- **File**: {filepath}
- **Records**: {len(records)}
- **Fields**: {len(first_record)}

## Statistical Summary

{chr(10).join([f"### {field}{chr(10)}- Sum: {stats['sum']}{chr(10)}- Average: {stats['avg']:.2f}{chr(10)}- Min: {stats['min']}{chr(10)}- Max: {stats['max']}{chr(10)}" for field, stats in statistics.items()])}

## Insights

{insights}

## Sample Data

```json
{json.dumps(records[:5], indent=2)}
```

---

*Generated by CloudCurio Data Analysis Pipeline*
"""
    
    # Save report
    writer = file_writer_tool({"base_path": "output"})
    report_filename = filepath.replace('.csv', '_analysis.md').replace('.json', '_analysis.md').split('/')[-1]
    
    writer_result = writer.execute(filepath=report_filename, content=report)
    
    if writer_result["status"] == "success":
        print(f"  Report saved: {writer_result['filepath']}")
    else:
        print(f"  Error saving report: {writer_result['error']}")
    
    return {
        "status": "success",
        "records_count": len(records),
        "statistics": statistics,
        "insights": insights,
        "report_path": writer_result.get("filepath", "")
    }


def compare_datasets(file1: str, file2: str) -> dict:
    """Compare two datasets.
    
    Args:
        file1: First dataset path
        file2: Second dataset path
    
    Returns:
        Comparison results
    """
    print(f"\nComparing datasets:")
    print(f"  {file1}")
    print(f"  {file2}")
    print("=" * 60)
    
    # Analyze both datasets
    result1 = analyze_dataset(file1)
    result2 = analyze_dataset(file2)
    
    if result1["status"] != "success" or result2["status"] != "success":
        return {"status": "error", "error": "Failed to analyze datasets"}
    
    # Generate comparison
    llm = llm_completion_tool({"temperature": 0.3})
    
    prompt = f"""Compare these two datasets:

Dataset 1: {file1}
- Records: {result1['records_count']}
- Statistics: {json.dumps(result1['statistics'], indent=2)}

Dataset 2: {file2}
- Records: {result2['records_count']}
- Statistics: {json.dumps(result2['statistics'], indent=2)}

Provide:
1. Key differences
2. Similarities
3. Trends across both
4. Recommendations

Be specific with numbers.
"""
    
    comparison = llm.execute(prompt=prompt)
    
    return {
        "status": "success",
        "comparison": comparison.get("text", ""),
        "dataset1": result1,
        "dataset2": result2
    }


def main():
    """Run data analysis pipeline."""
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python3 data_analysis_automation.py <datafile.csv|datafile.json>")
        print("       python3 data_analysis_automation.py <file1> <file2>  # Compare")
        return 1
    
    print("\n📊 Data Analysis Automation Pipeline")
    print("=" * 60)
    
    if len(sys.argv) == 2:
        # Single file analysis
        result = analyze_dataset(sys.argv[1])
        
        if result["status"] == "success":
            print("\n✓ Analysis complete!")
            print(f"  Records: {result['records_count']}")
            print(f"  Report: {result['report_path']}")
        else:
            print(f"\n✗ Failed: {result['error']}")
            return 1
    
    elif len(sys.argv) == 3:
        # Compare two datasets
        result = compare_datasets(sys.argv[1], sys.argv[2])
        
        if result["status"] == "success":
            print("\n✓ Comparison complete!")
        else:
            print(f"\n✗ Failed: {result['error']}")
            return 1
    
    print("\n" + "=" * 60)
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
